name: Deploy functions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  # python-formatting:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3
  #   - name: Setup Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: 3.9
  #   - name: Install dependencies
  #     run: pip install -r requirements.txt
  #   - name: Set PYTHONPATH to the api directory
  #     run: echo "PYTHONPATH=${{ github.workspace }}/api" >> $GITHUB_ENV
  #   - name: Find all Python files excluding the .venv directory
  #     run: find . -type f -name "*.py" ! -path "./.venv/*" -print0 > python_files.tmp
  #   - name: Run black
  #     run: xargs -0 black < python_files.tmp
  #   - name: Run flake8 (with adjustments to allow for black's formatting)
  #     run: xargs -0 flake8 < python_files.tmp --extend-ignore E203  --extend-ignore E722 --max-line-length 120
  #   - name: Run mypy
  #     run: |
  #       xargs -0 mypy --ignore-missing-imports < python_files.tmp
  #   - name: Clean up
  #     run: rm -f python_files.tmp

  # testing:
  #   runs-on: ubuntu-latest
  #   needs: python-formatting
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3
  #   - name: Setup Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: 3.9
  #   - name: Set environment variables
  #     env:
  #       SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  #       SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  #     run: |
  #       echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
  #       echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> $GITHUB_ENV
  #   - name: Set PYTHONPATH to the api directory
  #     run: | 
  #       echo "PYTHONPATH=${{ github.workspace }}/api" >> $GITHUB_ENV
  #   - name: List Python Modules in PYTHONPATH
  #     run: |
  #       python list_python_modules.py
  #   - name: Install dependencies
  #     run: pip install -r requirements.txt
  #   - name: Run unit tests
  #     run: | 
  #       pytest api/tests/unit/routes/*.py
  #       pytest api/tests/unit/services/*.py
  #       pytest api/tests/unit/models/*.py
  #       pytest api/tests/unit/utils/*.py
  #   - name: Run integration tests
  #     run: pytest api/tests/integration/*.py
  
    

  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Confirm Google Cloud Authentication
        run: gcloud auth list

      - name: Deploy api_check_email_in_use
        run: |
          gcloud functions deploy api_check_email_in_use \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_check_email_in_use
          --set-secrets=SUPABASE_URL=projects/projects/950999785047/secrets/SUPABASE_URL
          --set-secrets=SUPABASE_KEY=projects/projects/950999785047/secrets/SUPABASE_KEY

      - name: Deploy api_get_account_info
        run: |
          gcloud functions deploy api_get_account_info \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_get_account_info
          --set-secrets=SUPABASE_URL=projectsprojects/950999785047/secrets/SUPABASE_URL
          --set-secrets=SUPABASE_KEY=projects/projects/950999785047/secrets/SUPABASE_KEY

      - name: Deploy api_create_account
        run: |
          gcloud functions deploy api_create_account \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_create_account
          --set-secrets=SUPABASE_URL=projects/projects/950999785047/secrets/SUPABASE_URL
          --set-secrets=SUPABASE_KEY=projects/projects/950999785047/secrets/SUPABASE_KEY

      - name: Deploy api_update_account
        run: |
          gcloud functions deploy api_update_account \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_update_account
          --set-secrets=SUPABASE_URL=projects/projects/950999785047/secrets/SUPABASE_URL
          --set-secrets=SUPABASE_KEY=projects/projects/950999785047/secrets/SUPABASE_KEY

      - name: Deploy api_delete_account
        run: |
          gcloud functions deploy api_delete_account \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_delete_account
          --set-secrets=SUPABASE_URL=projects/projects/950999785047/secrets/SUPABASE_URL
          --set-secrets=SUPABASE_KEY=projects/projects/950999785047/secrets/SUPABASE_KEY